name: Run Macro Bot

on:
  schedule:
    - cron: "*/10 * * * *"  # каждые 10 минут
  workflow_dispatch:  # можно запускать вручную

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Устанавливаем зависимости
        run: pip install -r requirements.txt

      - name: Запускаем бота
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python app.py 
